server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: interface_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=mws, zksnmdys
            - name: CircuitBreaker
              args:
                name: fetchIngredients
                fallbackUri: forward:/fallback

        - id: ingredients-fallback
          uri: https://www.baidu.com
          predicates:
            - Path=/fallback

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace