server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: consumer
    qosEnable: true
    qosPort: 3333
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848?namespace=ba05aeb7-cc3d-4343-b088-23270418959b